const property = [
  {
    id: 1,
    location: "New York",
    status: "For Rent",
    address: "RCE Theaters- 907 S Becford Dr, Henderson, NC 27536",
    room: 3,
    bed: 4,
    bath: 1,
    area: 732,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1723278520/display_1500/stock-photo-cityscape-of-a-residential-area-with-modern-apartment-buildings-new-green-urban-landscape-in-the-1723278520.jpg",
    popular: true,
    price: 7225,
  },
  {
    id: 2,
    location: "Paris",
    status: "For Sale",
    address: "Costoco Wholesale-1021 Oak Forest Ln, Myrtle Beach",
    room: 3,
    bed: 4,
    bath: 1,
    area: 732,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1445600369/display_1500/stock-photo-eu-modern-european-complex-of-apartment-buildings-and-outdoor-facilities-mixed-media-1445600369.jpg",
    popular: false,
    price: 7225,
  },
  {
    id: 3,
    location: "Paris",
    status: "For Rent",
    address: "123 Rue de Rivoli, Paris, France",
    room: 2,
    bed: 3,
    bath: 1,
    area: 600,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1927887101/display_1500/stock-photo-apartment-residential-house-and-home-facade-architecture-and-outdoor-facilities-blue-sky-on-the-1927887101.jpg",
    popular: true,
    price: 7225,
  },
  {
    id: 4,
    location: "Mumbai",
    status: "For Sale",
    address: "456 Champs-Élysées, Paris, France",
    room: 3,
    bed: 4,
    bath: 2,
    area: 900,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1341854888/display_1500/stock-photo-modern-residential-buildings-in-the-city-d-rendering-1341854888.jpg",
    popular: false,
    price: 7225,
  },
  {
    id: 5,
    location: "Mumbai",
    status: "For Rent",
    address: "789 Marine Drive, Mumbai, India",
    room: 2,
    bed: 2,
    bath: 1,
    area: 800,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1918722533/display_1500/stock-photo-modern-apartment-building-in-the-countryside-in-a-residential-area-of-a-city-1918722533.jpg",
    popular: true,
    price: 7225,
  },
  {
    id: 6,
    location: "Mumbai",
    status: "For Sale",
    address: "101 Worli Sea Face, Mumbai, India",
    room: 3,
    bed: 3,
    bath: 2,
    area: 1000,
    image:
      "https://www.shutterstock.com/shutterstock/photos/265382324/display_1500/stock-photo-modern-apartment-buildings-265382324.jpg",
    popular: true,
    price: 7225,
  },
  {
    id: 6,
    location: "New York",
    status: "For Rent",
    address: "1234 Broadway, New York, NY, USA",
    room: 3,
    bed: 4,
    bath: 2,
    area: 1200,
    image:
      "https://www.shutterstock.com/shutterstock/photos/126936059/display_1500/stock-photo-modern-apartment-balcony-at-sunset-126936059.jpg",
    popular: false,
    price: 7225,
  },
  {
    id: 7,
    location: "New York",
    status: "For Sale",
    address: "567 Park Avenue, New York, NY, USA",
    room: 4,
    bed: 5,
    bath: 3,
    area: 1500,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1445600369/display_1500/stock-photo-eu-modern-european-complex-of-apartment-buildings-and-outdoor-facilities-mixed-media-1445600369.jpg",
    popular: false,
    price: 7225,
  },
  {
    id: 8,
    location: "Paris",
    status: "For Rent",
    address: "567 Park Avenue, New York, NY, USA",
    room: 4,
    bed: 5,
    bath: 3,
    area: 1500,
    image:
      "https://www.shutterstock.com/shutterstock/photos/1723278520/display_1500/stock-photo-cityscape-of-a-residential-area-with-modern-apartment-buildings-new-green-urban-landscape-in-the-1723278520.jpg",
    popular: false,
    price: 7225,
  },
];

export default property;
